name: S3 Deploy 

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  BUILD_CONFIG: prod

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js $
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json
            **/node_modules


      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

      - name: Build Angular App
        run: npm run build-$BUILD_CONFIG

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET }}
          aws-region: $AWS_REGION
      - name: Deploy to S3
        run: |
          aws s3 sync \
            --delete \
            --exclude ".git/*" \
            --exclude .gitignore \
            --exclude ".github/*" \
            --exclude README.md \
            dist/victory-nachos/ s3://kjr-static-content/sites/victorynachos.com/$BUILD_CONFIG/
      - name: Clear CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id E1LISWFGXI75S3 --region us-east-1 --paths  "/*" "/"
