name: S3 Deploy 

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  BUILD_CONFIG: prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master


      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        run: npm install

      - name: Build
        run: npm run build-prod

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_SECRET }}
        run: |
          aws s3 sync \
            --delete \
            --exclude ".git/*" \
            --exclude .gitignore \
            --exclude ".github/*" \
            --exclude README.md \
            --region $AWS_REGION \
            dist/victory-nachos/ s3://kjr-static-content/sites/victorynachos.com/$BUILD_CONFIG/

      - name: Clear CloudFront
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_SECRET }}
        run: |
          aws cloudfront create-invalidation --distribution-id E1LISWFGXI75S3 --region $AWS_REGION --paths  "/*" "/"
